#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        ammo[] = {
            "BulletBase",
            "ShellCore",
            "SubmunitionBase",
            "MissileCore",
            "Gatling_30mm_HE_Plane_CAS_01_F",
            "GrenadeCore",
            "BombCore",
            "LaserBombCore",
            "RocketCore",
            "ShellBase",
            "MissileBase",
            "RocketBase",
            "Grenade",
            "GrenadeHand",
            "SmokeShell",
            "GrenadeBase",
            "FuelExplosion",
            "FuelExplosionBig",
            "HelicopterExploSmall",
            "HelicopterExploBig",
            "SmallSecondary",
            "B_19mm_HE",
            "B_30mm_HE",
            "B_30mm_HE_Tracer_Red",
            "B_30mm_HE_Tracer_Green",
            "B_30mm_HE_Tracer_Yellow",
            "B_30mm_MP",
            "B_30mm_MP_Tracer_Red",
            "B_30mm_MP_Tracer_Green",
            "B_30mm_MP_Tracer_Yellow",
            "B_40mm_GPR","B_40mm_GPR_Tracer_Red",
            "B_40mm_GPR_Tracer_Green",
            "B_40mm_GPR_Tracer_Yellow",
            "B_20mm","B_20mm_Tracer_Red",
            "B_25mm","B_30mm_AP",
            "B_30mm_AP_Tracer_Red",
            "B_30mm_AP_Tracer_Green",
            "B_30mm_AP_Tracer_Yellow",
            "B_30mm_APFSDS",
            "B_30mm_APFSDS_Tracer_Red",
            "B_30mm_APFSDS_Tracer_Green",
            "B_30mm_APFSDS_Tracer_Yellow",
            "B_40mm_APFSDS",
            "B_35mm_AA",
            "M_PG_AT",
            "M_AT",
            "M_Mo_82mm_AT",
            "M_Mo_82mm_AT_LG",
            "M_Mo_120mm_AT",
            "M_Mo_120mm_AT_LG",
            "M_RPG32_F",
            "M_RPG32_AA_F",
            "M_NLAW_AT_F",
            "M_Scalpel_AT",
            "M_Scalpel_AT_hidden",
            "M_Titan_AA",
            "M_Zephyr",
            "M_Zephyr_Mi06",
            "M_Air_AA",
            "M_Air_AA_MI02",
            "M_Titan_AT",
            "M_Titan_AP",
            "M_Air_AT",
            "R_80mm_HE",
            "R_60mm_HE",
            "R_230mm_HE",
            "R_230mm_fly",
            "Sh_120mm_HE",
            "Sh_120mm_HE_Tracer_Red",
            "Sh_120mm_HE_Tracer_Green",
            "Sh_120mm_HE_Tracer_Yellow",
            "Sh_120mm_APFSDS",
            "Sh_120mm_APFSDS_Tracer_Red",
            "Sh_120mm_APFSDS_Tracer_Green",
            "Sh_120mm_APFSDS_Tracer_Yellow",
            "Sh_155mm_AMOS",
            "Sh_82mm_AMOS",
            "Sh_82mm_AMOS_guided",
            "Sh_82mm_AMOS_LG",
            "Sh_155mm_AMOS_guided",
            "Sh_155mm_AMOS_LG","G_40mm_HE",
            "G_20mm_HE",
            "G_40mm_HEDP",
            "MineBase",
            "BoundingMineBase",
            "DirectionalBombBase",
            "PipeBombBase",
            "ATMine_Range_Ammo",
            "UnderwaterMine_Range_Ammo",
            "UnderwaterMineAB_Range_Ammo",
            "UnderwaterMinePDM_Range_Ammo",
            "APERSMine_Range_Ammo",
            "APERSBoundingMine_Range_Ammo",
            "SLAMDirectionalMine_Wire_Ammo",
            "APERSTripMine_Wire_Ammo",
            "ClaymoreDirectionalMine_Remote_Ammo",
            "SatchelCharge_Remote_Ammo",
            "DemoCharge_Remote_Ammo",
            "IEDUrbanBig_Remote_Ammo",
            "IEDLandBig_Remote_Ammo",
            "IEDUrbanSmall_Remote_Ammo",
            "IEDLandSmall_Remote_Ammo",
            "Bo_Mk82"    
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "keko_main"
        };
        author = "Schwaggot";
        authors[] = {"Schwaggot"};
        url = ECSTRING(main,URL);
        VERSION_CONFIG;
    };
};

#include "CfgEventHandlers.hpp"
#include "CfgAmmo.hpp"
